function(use_runtime type)
    if(type STREQUAL "dynamic")
        if(MSVC)
            # Dynamic runtime (DLL) for MSVC
            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL$<$<CONFIG:Debug>:Debug>")
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            # Remove static runtime flags, enforce dynamic linking (default behavior)
            string(REPLACE "-static-libgcc" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
            string(REPLACE "-static-libstdc++" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
            string(REPLACE "-static" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Intel")
            if(MSVC)
                set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL$<$<CONFIG:Debug>:Debug>")
            else()
                string(REPLACE "-static-libgcc" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
                string(REPLACE "-static-libstdc++" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
                string(REPLACE "-static" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
            endif()
        else()
            message(FATAL_ERROR "Invalid compiler: ${CMAKE_CXX_COMPILER_ID}")
        endif()
    elseif(type STREQUAL "static")
        if(MSVC)
            # MSVC static runtime (recommended CMake 3.15+ way)
            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            if(WIN32)
                # MinGW or Clang on Windows, static libgcc/libstdc++
                set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++")
            else()
                # Linux/macOS Clang or GCC, link libgcc/libstdc++ statically (optional)
                set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++")
            endif()
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Intel")
            if(MSVC)
                set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
            else()
                set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++")
            endif()
        else()
            message(FATAL_ERROR "Invalid compiler: ${CMAKE_CXX_COMPILER_ID}")
        endif()
    else()
        message(FATAL_ERROR "Invalid runtime type: ${type}")
    endif()
endfunction()
